### PR TITLE
elfutils: use more secure ptrace scope configuration by default

### PR DESCRIPTION
**Pull request by christopherco**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] If you are adding/removing a .spec file that has multiple-versions supported, please add [@microsoft/cbl-mariner-multi-package-reviewers](https://github.com/orgs/microsoft/teams/cbl-mariner-multi-package-reviewers) team as reviewer [(Eg. golang has 2 versions 1.18, 1.21+)](https://github.com/microsoft/azurelinux/tree/2.0/SPECS/golang)
- [x] Ready to merge

---

###### Summary 

By default, set the yama ptrace_scope configuration to "1" meaning to
only allow restricted ptrace attach to child processes. This is the
more secure default setting for the system.

Users can opt to change this setting by changing the sysctl option to
"0" if they need unrestricted ptrace attach properties for things like
debugging.

Signed-off-by: Chris Co <chrco@microsoft.com>

###### Does this affect the toolchain?  

**YES**

###### Associated issues  

- https://microsoft.visualstudio.com/OS/_workitems/edit/51548629

###### Test Methodology

- Pipeline build id: [592753](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=592753&view=results)

### CODE REVIEW

**Review by anphel31 — COMMENTED** [review]
I'd suggest running a toolchain build for extra validation, in addition to the buddybuild. I've started one for this PR: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593224&view=results

**Review by anphel31 — APPROVED** [review]
Approved, but can you please check on the toolchain build before merging? https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593224&view=results

**Comment by christopherco** [comment]
> Approved, but can you please check on the toolchain build before merging? https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593224&view=results

toolchain builds passed:
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593232&view=results
- https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593233&view=results

**Comment by anphel31** [comment]
> Approved, but can you please check on the toolchain build before merging? https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593224&view=results

Looks like the toolchain builds are ok.
X64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593232&view=results
ARM64: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=593233&view=results

**Pull request merged**
