### PR TITLE
Drop multilib-rpm-config

### PR DESCRIPTION
**Pull request by dmcilvaney**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

`multilib-rpm-config` is a a set of scripts from Fedora, take a very minor update to align with upstream f40 version.

###### Change Log  

- Align `multilib-rpm-configs` with f40.

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=547372&view=results

### CODE REVIEW

**Review by jslobodzian — CHANGES_REQUESTED** [review]
Mariner doesn't support multilib.  Do we know why we have this?

**Comment by dmcilvaney** [comment]
> Mariner doesn't support multilib. Do we know why we have this?

Running `depsearch` I see
mariadb-connector-c
openblas

I'll look into these, see if this is actually  needed. These cascade into 246 packages across the graph.

**Comment by dmcilvaney** [comment]
Did some digging, I think we can indeed drop this completely.

**Comment by dmcilvaney** [comment]
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=547372&view=results

**Review by jslobodzian — APPROVED** [review]

**Pull request merged**
