### PR TITLE
TDX: Enable CONFIG_INTEL_TDX_GUEST, CONFIG_TDX_GUEST_DRIVER

### PR DESCRIPTION
**Pull request by Ankita13-code**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Enable `CONFIG_INTEL_TDX_GUEST`, `CONFIG_TDX_GUEST_DRIVER` for CVM images. These configs bring in support for Intel TDX machines.

###### Change Log  

- Set `CONFIG_INTEL_TDX_GUEST=y` -> [Kconfig](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-3/6.6.61.1/arch/x86/Kconfig#L879) for Supporting running as a guest under Intel TDX
- Set `CONFIG_TDX_GUEST_DRIVER=m` -> [Kconfig](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-3/6.6.61.1/drivers/virt/coco/tdx-guest/Kconfig#L1) for enabling the driver which provides userspace interface to communicate with the TDX module to request the TDX guest details like attestation report.

###### Does this affect the toolchain?  

**YES**

###### Associated issues  

- [46616758](https://dev.azure.com/microsoft/OS/_workitems/edit/46616758)

###### Test Methodology

- Local build passes
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=691222&view=results
Tested on Azure CVM that support Intel TDX - 
image

### CODE REVIEW

**Comment by trungams** [comment]
any mention of TDX in dmesg output?

**Comment by Ankita13-code** [comment]
> any mention of TDX in dmesg output?

image
 Here is the dmesg output

**Comment by ms-mahuber** [comment]
TODO:
1. to confirm this was also booted as a regular CVM
2. to rebase. there's an upgrade from 57 to 62 going on
3. to confirm we want the guest driver built-in, not as a module

**Comment by Ankita13-code** [comment]
> * to confirm this was also booted as a regular VM
> * to rebase. there's an upgrade from 57 to 62 going on at the same time: [[AUTOPATCHER-kernel] Kernel upgrade to version 6.6.62.1 - branch 3.0-dev #11282](https://github.com/microsoft/azurelinux/pull/11282)
> * TDX_GUEST_DRIVER as `=m` (module)

@ms-mahuber The image booted fine as a regular VM. Incorporated all the other requested changes as well.

**Review by ms-mahuber — APPROVED** [review]

**Review by rlmenge — APPROVED** [review]
:shipit:

**Review by christopherco — APPROVED** [review]

**Review by trungams — APPROVED** [review]

**Pull request merged**
