### PR TITLE
Package argparse-manpage naming convention consistency

### PR DESCRIPTION
**Pull request by AZaugg**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [x] If you are adding/removing a .spec file that has multiple-versions supported, please add [@microsoft/cbl-mariner-multi-package-reviewers](https://github.com/orgs/microsoft/teams/cbl-mariner-multi-package-reviewers) team as reviewer [(Eg. golang has 2 versions 1.18, 1.21+)](https://github.com/microsoft/azurelinux/tree/2.0/SPECS/golang)
- [X] Ready to merge

---

###### Summary 

Renaming package name argparse-manpage -> python-argparse-manpage

To be consistent, all python pypi modules are named python-<name> the
 package argparse-manpage does not follow this convention, updating base
package name to be consistent.

###### Change Log  

- Rename package

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Built package via toolchain
```
INFO[0000][scheduler] Reading DOT graph from /home/azaugg/azurelinux/build/pkg_artifacts/preprocessed_graph.dot
INFO[0000][scheduler] Reading DOT graph from /home/azaugg/azurelinux/build/pkg_artifacts/preprocessed_graph.dot
INFO[0000][scheduler] Successfully created solvable subgraph
INFO[0000][scheduler] Building 8 nodes with 16 workers
INFO[0000][scheduler] Building: argparse-manpage-1.5-3.cm2.src.rpm
INFO[0017][scheduler] Built: argparse-manpage-1.5-3.cm2.src.rpm -> [/home/azaugg/azurelinux/out/RPMS/noarch/argparse-manpage-1.5-3.cm2.noarch.rpm /home/azaugg/azurelinux/out/RPMS/noarch/python3-argparse-manpage-1.5-3.cm2.noarch.rpm]
INFO[0017][scheduler] 0 currently active build(s): [].
INFO[0017][scheduler] SRPM (python3-argparse-manpage:C:'='V:'1.5-3.cm2',C2:''V2:'') will be rebuilt due to user request.
INFO[0017][scheduler] SRPM (argparse-manpage:C:'='V:'1.5-3.cm2',C2:''V2:'') will be rebuilt due to user request.
INFO[0017][scheduler] All packages built
INFO[0018][scheduler] ---------------------------
INFO[0018][scheduler] --------- Summary ---------
INFO[0018][scheduler] ---------------------------
INFO[0018][scheduler] Number of prebuilt SRPMs:           0
INFO[0018][scheduler] Number of prebuilt delta SRPMs:     0
INFO[0018][scheduler] Number of skipped SRPMs tests:      0
INFO[0018][scheduler] Number of built SRPMs:              1
INFO[0018][scheduler] Number of passed SRPMs tests:       0
INFO[0018][scheduler] Number of unresolved dependencies:  0
INFO[0018][scheduler] Number of blocked SRPMs:            0
INFO[0018][scheduler] Number of blocked SRPMs tests:      0
INFO[0018][scheduler] Number of failed SRPMs:             0
INFO[0018][scheduler] Number of failed SRPMs tests:       0
INFO[0018][scheduler] Number of toolchain RPM conflicts:  0
INFO[0018][scheduler] Number of toolchain SRPM conflicts: 0
INFO[0018][scheduler] Built SRPMs:
INFO[0018][scheduler] --> argparse-manpage-1.5-3.cm2.src.rpm
INFO[0018][scheduler] ---------------------------
INFO[0018][scheduler] --------- Summary ---------
INFO[0018][scheduler] ---------------------------
INFO[0018][scheduler] Number of prebuilt SRPMs:           0
INFO[0018][scheduler] Number of prebuilt delta SRPMs:     0
INFO[0018][scheduler] Number of skipped SRPMs tests:      0
INFO[0018][scheduler] Number of built SRPMs:              1
INFO[0018][scheduler] Number of passed SRPMs tests:       0
INFO[0018][scheduler] Number of unresolved dependencies:  0
INFO[0018][scheduler] Number of blocked SRPMs:            0
INFO[0018][scheduler] Number of blocked SRPMs tests:      0
INFO[0018][scheduler] Number of failed SRPMs:             0
INFO[0018][scheduler] Number of failed SRPMs tests:       0
INFO[0018][scheduler] Number of toolchain RPM conflicts:  0
INFO[0018][scheduler] Number of toolchain SRPM conflicts: 0
INFO[0018][scheduler] Writing DOT graph to /home/azaugg/azurelinux/build/pkg_artifacts/built_graph.dot
INFO[0018][scheduler] Waiting for outstanding processes to be created
Finished updating /home/azaugg/azurelinux/out/RPMS
```

Confirmed that no other package makes reference to this package in the repo
```
azaugg@azaugg-ld1 [ ~/azurelinux ] [ argparse-manpage-renmae ] $ git grep argparse-manpage
LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md:LICENSES-AND-NOTICES/SPECS/data/licenses.json:                "python-argparse-manpage",
SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.signatures.json:  "argparse-manpage-1.5.tar.gz": "0caa9d7a175f4c76853756814facc017d99d1ca3493b8982911aed82747c73f8"
SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.spec:Name:           argparse-manpage
SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.spec:%{_bindir}/argparse-manpage
SPECS-EXTENDED/python-argparse-manpage/python-argparse-manpage.spec:%{_mandir}/man1/argparse-manpage.1.*
cgmanifest.json:          "name": "python-argparse-manpage",
cgmanifest.json:          "downloadUrl": "https://files.pythonhosted.org/packages/source/a/argparse-manpage/argparse-manpage-1.5.tar.gz"
```

### CODE REVIEW

**Comment by AZaugg** [comment]
Ran a buddy build https://dev.azure.com/mariner-org/mariner/_build/results?buildId=588021&view=results

**Review by christopherco — APPROVED** [review]

**Review by christopherco — CHANGES_REQUESTED** [review]
buddy build failure - investigating...

**Comment by AZaugg** [comment]
Odd. I ran a buddy build earlier. I can take a look a little later

**Review by christopherco — APPROVED** [review]
Buddy Builds are now passing - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=590426&view=results

**Pull request merged**
