### PR TITLE
Add patch to add network interface renaming support for CAPM3 Met

### PR DESCRIPTION
**Pull request by sharath-srikanth-chellappa**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] If you are adding/removing a .spec file that has multiple-versions supported, please add [@microsoft/cbl-mariner-multi-package-reviewers](https://github.com/orgs/microsoft/teams/cbl-mariner-multi-package-reviewers) team as reviewer [(Eg. golang has 2 versions 1.18, 1.21+)](https://github.com/microsoft/azurelinux/tree/2.0/SPECS/golang)
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

Add patch to add network interface renaming support for CAPM3 Met.
This patch is being attached from our internal afo-packages for now, however, we want it to be applied to AZL directly.

###### Change Log  

- Add patch to add network interface renaming support for CAPM3 Met.
- Make changes to the pkg tests to work with the patch introduced

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566646&view=results

### CODE REVIEW

**Review by romoh — APPROVED** [review]

**Review by PawelWMS — CHANGES_REQUESTED** [review]
Blocking until we understand the priority of this work item and/if it's needed in 2.0 instead of 3.0 version of Azure Linux. At the moment this topic seems to be not entirely clear.

**Comment by sharath-srikanth-chellappa** [comment]
> Blocking until we understand the priority of this work item and/if it's needed in 2.0 instead of 3.0 version of Azure Linux. At the moment this topic seems to be not entirely clear.

Hey Pawel. The current patch that was added is something that we already have as part of `afo-packages` (https://dev.azure.com/mariner-org/ECF/_git/afo-packages?path=/build-scripts/patches/cloud-init/patches/Add-Network-Interface-Renaming-Support-for-CAPM3-Met.patch)

The reason why this is being added here is because Nexus is moving to use MIC. And in order for them to use MIC, the same patches would have to be present on CBL-Mariner I believe.

**Review by rmhsawyer — COMMENTED** [review]
Please test this change by successfully deploying an Azure VM and make sure no "WARNING/ERROR" message in /var/log/cloud-init.log introduced by this change

**Comment by sharath-srikanth-chellappa** [comment]
> Please test this change by successfully deploying an Azure VM and make sure no "WARNING/ERROR" message in /var/log/cloud-init.log introduced by this change

Aren't these already covered in a successful FastTrack 2.0 dev pipeline run  - 
[Pipelines - Run 2.0.20240509-fasttrack-566704 (azure.com)](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=566704&view=results)

This check should be covered there right ?

**Comment by PawelWMS** [comment]
Merging - one failing ptests in `libguestfs` but not triggered by this change.

**Pull request merged**
