### PR TITLE
[2.0] dhcp/dhclient.conf: add option rfc3442-classless-static-routes in dhclient.conf

### PR DESCRIPTION
**Pull request by cjp256**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

Azure configures classless routes and cloud-init requires the configuration to be included in the lease file to behave correctly.

###### Change Log  

- Add rfc3442-classless-static-routes option to dhclient.conf

###### Does this affect the toolchain?  

No

###### Test Methodology

Build & installed RPM locally and validated cloud-init behavior.

### CODE REVIEW

**Review by mfrw — COMMENTED** [review]
Can we please retarget this change to `main`.
Anything that has to go to `2.0` goes via `main` :)

**Comment by cjp256** [comment]
Fixes https://github.com/microsoft/azurelinux/issues/8334

**Comment by cjp256** [comment]
> Can we please retarget this change to `main`. Anything that has to go to `2.0` goes via `main` :)

Done, thanks!

**Review by ddstreetmicrosoft — APPROVED** [review]
Thanks for #8334, it clearly explains the issue and after reading that this LGTM

We should add this to 3.0 as well, can you open a PR against 3.0-dev also?

**Review by dmcilvaney — APPROVED** [review]
Cleaned up some spurious required reviews (probably a leftover from 2.0 target). Dropped tooling and admins. That said I don't see any issues with the change.

**Pull request merged**
