### PR TITLE
add patch for cloud-init pkg install error

### PR DESCRIPTION
**Pull request by rmhsawyer**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Mariner in 2.0 inherited some cloud-init provisioning functions from photon in [upstream](https://github.com/canonical/cloud-init/blob/f7c1c76104870b629d3b5e25618544431f7d8427/cloudinit/distros/photon.py) which includes package install function. This function logs error even on benign warning message. For example, doing tdnf upgrade with message "None or nothing to do" will be consider as an error. This causes some issues for Mariner users trying to use cloud-init package install provisioning function. Here we add a change to prevent exec_cmd returning failure if stderr is present. If something comes up in the package install process, we will still be able to catch it in the cloud-init.log.

###### Change Log  

- add a patch to prevent return error in cloud-init exec_cmd function
- adjust unit test accordingly

###### Does this affect the toolchain?  

NO

###### Associated issues  

- [Bug 48639553](https://microsoft.visualstudio.com/OS/_workitems/edit/48639553): For Mariner 2: 2 ClusterConfiguration Package download is failing for multiple packages

###### Test Methodology

- local package build with RUN_CHECK=y
- Buddy build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=529575&view=results
- Azure VM provisioning test using package install module

### CODE REVIEW

**Comment by cjp256** [comment]
Looks like exec_cmd() assumes return failure if stderr is present.  https://github.com/canonical/cloud-init/blob/82a5fb3588102b088c84def3a263d4c2d61fcb0f/cloudinit/distros/photon.py#L48

Maybe it's worth patching that instead?

**Comment by ddstreetmicrosoft** [comment]
> Looks like exec_cmd() assumes return failure if stderr is present. https://github.com/canonical/cloud-init/blob/82a5fb3588102b088c84def3a263d4c2d61fcb0f/cloudinit/distros/photon.py#L48
> 
> Maybe it's worth patching that instead? Doesn't look like an appropriate assumption in the general case.

I agree this is a better approach.

**Comment by rmhsawyer** [comment]
> > Looks like exec_cmd() assumes return failure if stderr is present. https://github.com/canonical/cloud-init/blob/82a5fb3588102b088c84def3a263d4c2d61fcb0f/cloudinit/distros/photon.py#L48
> > Maybe it's worth patching that instead? Doesn't look like an appropriate assumption in the general case.
> 
> I agree this (patching exec_cmd) is a better approach.

**Comment by cjp256** [comment]
LGTM, thanks!  Perhaps that stderr check appears to have been for setting hostname? Maybe we can try to set an invalid hostname and make sure it fails properly on Mariner?

**Review by ddstreetmicrosoft — APPROVED** [review]
lgtm

**Pull request merged**
