### PR TITLE
Add configurability in systemd to control default value of UseDomains parameter

### PR DESCRIPTION
**Pull request by henryli001**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

- Adds parameters to /etc/systemd/networkd.conf to allow controlling the default value of the UseDomain= parameter (for both dhcp v4 and v6). 
- Backported from this [change](https://github.com/systemd/systemd/pull/32194) in the upstream

###### Change Log  

- Add patch to allow configurability of "UseDomains=" for networkd

###### Does this affect the toolchain?  

NO

###### Test Methodology

- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=550114&view=results

### CODE REVIEW

**Comment by ddstreetmicrosoft** [comment]
technically looks ok, but these kind of user-facing parameters are dangerous to add into stable releases *before* upstreaming; we do not want to add and release a config param that our users start using, and then have upstream decide they want to do it differently, leaving us to clean up our own mess of having a parameter that (at best) is confusing to end users and adds maintenance burden or (at worst) directly conflicts with how upstream decides to implement it.

So with the caveat that this needs to be upstreamed *first*, it LGTM.

**Comment by henryli001** [comment]
> technically looks ok, but these kind of user-facing parameters are dangerous to add into stable releases _before_ upstreaming; we do not want to add and release a config param that our users start using, and then have upstream decide they want to do it differently, leaving us to clean up our own mess of having a parameter that (at best) is confusing to end users and adds maintenance burden or (at worst) directly conflicts with how upstream decides to implement it.
> 
> So with the caveat that this needs to be upstreamed _first_, it LGTM.

Makes sense to me. Will start working on the upstream change first and post the link here.

**Comment by henryli001** [comment]
> > technically looks ok, but these kind of user-facing parameters are dangerous to add into stable releases _before_ upstreaming; we do not want to add and release a config param that our users start using, and then have upstream decide they want to do it differently, leaving us to clean up our own mess of having a parameter that (at best) is confusing to end users and adds maintenance burden or (at worst) directly conflicts with how upstream decides to implement it.
> > So with the caveat that this needs to be upstreamed _first_, it LGTM.
> 
> Makes sense to me. Will start working on the upstream change first and post the link here.

Upstream changes have been merged in: https://github.com/systemd/systemd/pull/32194. Updated the patch here to align with the upstream changes.

**Comment by henryli001** [comment]
> LGTM but please patch azl3 also (preferably first)

3.0 patching complete. Here's the PR link: https://github.com/microsoft/azurelinux/pull/8799

**Review by dallasd1 — APPROVED** [review]

**Review by hbeberman — APPROVED** [review]

**Pull request merged**
