### PR TITLE
Add virtiofsd 

### PR DESCRIPTION
**Pull request by kanikanema**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 
Add virtiofsd v1.10.1 required by qemu

###### Change Log  
Starting qemu 8.0.0 qemu-virtiofsd has been deprecated and no longer bundled. In 3.0 qemu will be at 8.2.0 and has a dependency on this package.

###### Test Methodology
Local build: 
image

Buddy Build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=501605&view=logs&s=996d21db-341a-52f1-405f-05cafe2a50b7

### CODE REVIEW

**Comment by christopherco** [comment]
Tagging @sprt who introduced virtiofsd into our 2.0 branch recently as a dependency for kata-containers - https://github.com/microsoft/CBL-Mariner/pull/7215 .

**Comment by kanikanema** [comment]
Thanks for the details @sprt. Because kata has a strong dependency on virtiofsd v1.8, it might be better that we crossport this from main (2.0). 
All the following hold for this PR (and will work for qemu v8.2.0 that will be added in 3.0) except that it is at v1.10.0

- Assuming QEMU 8.0 requiring vhostuser-backend(fs)​
Remove qemu-virtiofsd​
Introduce Rust package virtiofsd​
Binary in the previous C binary location​
Provides: vhostuser-backend(fs) => we install the JSON file in the qemu location ourselves, we create it if needed​
NO Requires: qemu-common

AFAICS, qemu > v8.0 should work with virtiofsd v1.8 onwards so adding 1.8 instead of 1.10 should be acceptable for 3.0.

**Comment by kanikanema** [comment]
Hi @sprt, this PR has all online and offline review comments addressed. If we do plan to support v1.10.1 then this PR can go in as is. As discussed, please take over the PR and merge it as appropriate so that it doesn't break kata.
Please do prioritize this since qemu has a dependency on it and we can't install the new qemu package without this. Thanks.

**Comment by sprt** [comment]
Passing buddy build following the change to v1.8.0: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=518254&view=results

**Review by sprt — APPROVED** [review]

**Review by ms-mahuber — APPROVED** [review]

**Pull request merged**
