### PR TITLE
Upgrade createrepo_c to 1.0.3

### PR DESCRIPTION
**Pull request by suresh-thelkar**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Upgrade createrepo_c to 1.0.3

###### Change Log  

- NA

###### Does this affect the toolchain?  

**YES**

###### Associated issues  

- NA

###### Links to CVEs  
- NA

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Comment by mbykhovtsev-ms** [comment]
> This PR needs to go after the PR #7837 gets merged.

The PR was merged, but I still have couple of infrastructure PRs that I need to be merged first before this one to make sure nothing breaks in builds and tests

**Comment by suresh-thelkar** [comment]
> > This PR needs to go after the PR #7837 gets merged.
> 
> The PR was merged, but I still have couple of infrastructure PRs that I need to be merged first before this one to make sure nothing breaks in builds and tests. I will reply once it is good to go

Thanks @mbykhovtsev-ms for the update. I will wait for your reply.

**Comment by mbykhovtsev-ms** [comment]
> > > This PR needs to go after the PR #7837 gets merged.
> > 
> > 
> > The PR was merged, but I still have couple of infrastructure PRs that I need to be merged first before this one to make sure nothing breaks in builds and tests. I will reply once it is good to go
> 
> Thanks @mbykhovtsev-ms for the update. I will wait for your reply and proceed accordingly.

@suresh-thellkar. All infrastructure PRs have been merged. We should be ready for this PR now.

**Comment by mbykhovtsev-ms** [comment]
> > > > This PR needs to go after the PR #7837 gets merged.
> > > 
> > > 
> > > The PR was merged, but I still have couple of infrastructure PRs that I need to be merged first before this one to make sure nothing breaks in builds and tests. I will reply once it is good to go
> > 
> > 
> > Thanks @mbykhovtsev-ms for the update. I will wait for your reply and proceed accordingly.
> 
@suresh-thelkar . All infrastructure PRs have been merged. We should be ready for this PR now.

**Review by mbykhovtsev-ms — APPROVED** [review]

**Comment by suresh-thelkar** [comment]
> > > > This PR needs to go after the PR #7837 gets merged.
> > > 
> > > 
> > > The PR was merged, but I still have couple of infrastructure PRs that I need to be merged first before this one to make sure nothing breaks in builds and tests. I will reply once it is good to go
> > 
> > 
> > Thanks @mbykhovtsev-ms for the update. I will wait for your reply and proceed accordingly.
> 
> @suresh-thelkar . All infrastructure PRs have been merged. We should be ready for this PR now.

Thank you very much for your help and review.

**Review by anphel31 — APPROVED** [review]

**Comment by suresh-thelkar** [comment]
Thanks @anphel31 / @mbykhovtsev-ms for your help and reviews.

**Pull request merged**
