### PR TITLE
Add packages subunit and python-junitxml

### PR DESCRIPTION
**Pull request by joejoew**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Add package subunit and it's dependency python-junitxml for building HPC image

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- pipeline build: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642053&view=results

### CODE REVIEW

**Review by anphel31 — COMMENTED** [review]
Can you please run a buddybuild? https://dev.azure.com/mariner-org/mariner/_build?definitionId=2190&_a=summary

**Comment by joejoew** [comment]
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642053&view=results
Done

**Review by anphel31 — COMMENTED** [review]
It looks like we used to have the `subunit` package in SPECS-EXTENDED, but it was removed because some runtime dependencies were missing (see: https://github.com/microsoft/azurelinux/pull/5244). Can you confirm those are now present?

**Comment by anphel31** [comment]
> Member

I've started a delta build to see if it helps confirm the runtime dependencies. https://dev.azure.com/mariner-org/mariner/_build/results?buildId=642184&view=results

**Comment by joejoew** [comment]
Yes, runtime dependency is python-junitxml

**Review by anphel31 — APPROVED** [review]

**Pull request merged**
