### PR TITLE
kernel: config_aarch64: convert selected configs to modules

### PR DESCRIPTION
**Pull request by kelsey-steele**
Moving batch of configs that were built-in to be modules to maintain flexibility, though reduce kernel size and boot speed.

These modules are already set as modules on x86 and only targeted to change on arm64.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] If you are adding/removing a .spec file that has multiple-versions supported, please add [@microsoft/cbl-mariner-multi-package-reviewers](https://github.com/orgs/microsoft/teams/cbl-mariner-multi-package-reviewers) team as reviewer [(Eg. golang has 2 versions 1.18, 1.21+)](https://github.com/microsoft/azurelinux/tree/2.0/SPECS/golang)
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

Moving batch of configs that were built-in to be modules to maintain flexibility, though reduce kernel size and boot speed.

These modules are already set as modules on x86 and only targeted to change on arm64.

###### Does this affect the toolchain?  

No, does not affect the toolchain

### CODE REVIEW

**Comment by kelsey-steele** [comment]
Hi @rlmenge o/  

Here's the config PR I mentioned to you before. Can you please review when you have a cycle? Thank you! :)

**Review by rlmenge — COMMENTED** [review]
Started a BuddyBuild here: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=592126&view=results

I am using a test branch "[rlmenge/kelsey/user/kms/x86-kernel-config-updates](https://github.com/microsoft/azurelinux/tree/rlmenge/kelsey/user/kms/x86-kernel-config-updates)" which also updates the relevant SPEC files

**Comment by kelsey-steele** [comment]
Hi @christopherco  o/  

Can you or know someone who can please help finish this review while Rachel is away? I believe I managed to catch all the version updates this time. :)

**Comment by christopherco** [comment]
Buddy Build passed https://dev.azure.com/mariner-org/mariner/_build/results?buildId=612195&view=results

**Review by christopherco — APPROVED** [review]
:shipit:

**Review by dmcilvaney — APPROVED** [review]

**Pull request merged**
