### PR TITLE
Toolkit: Fix JSON parsing of util-linux commands.

### PR DESCRIPTION
**Pull request by cwize1**
Prior to util-linux v2.37, when a command is outputting a list in JSON and there aren't any items, then stdout would be empty. This change checks for this scenario and handles it appropriately.

---

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] If you are adding/removing a .spec file that has multiple-versions supported, please add [@microsoft/cbl-mariner-multi-package-reviewers](https://github.com/orgs/microsoft/teams/cbl-mariner-multi-package-reviewers) team as reviewer [(Eg. golang has 2 versions 1.18, 1.21+)](https://github.com/microsoft/azurelinux/tree/2.0/SPECS/golang)
- [x] Ready to merge

###### Does this affect the toolchain?  

NO

###### Bug
https://microsoft.visualstudio.com/OS/_workitems/edit/52123611

###### Test Methodology

- Manually ran the image customizer tool.

### CODE REVIEW

**Review by PawelWMS — COMMENTED** [review]
The change looks good. From what I know, I think we're not allowing any changes, which are not considered 3.0 GA blockers, so can you check, if this change may go in? Personally, I think it's small and safe.

**Comment by cwize1** [comment]
> The change looks good. From what I know, I think we're not allowing any changes, which are not considered 3.0 GA blockers, so can you check, if this change may go in? Personally, I think it's small and safe.

This is actively blocking ISO building for ARM64.

**Comment by PawelWMS** [comment]
> > The change looks good. From what I know, I think we're not allowing any changes, which are not considered 3.0 GA blockers, so can you check, if this change may go in? Personally, I think it's small and safe.
> 
> This is actively blocking ISO building for ARM64.

Sounds like a GA blocker then. Please add a link to the bug for this in the summary, so it's easier to track.

**Comment by dmcilvaney** [comment]
Added bug link https://microsoft.visualstudio.com/OS/_workitems/edit/52123611

**Review by dmcilvaney — CHANGES_REQUESTED** [review]
Since Ubuntu 18.04 is EOL this isn't considered a critical bug. Wait for GA stabilization and release to be done, can merge after.

**Review by dmcilvaney — COMMENTED** [review]
Looks like Ubuntu 20.04 also has an old version of util-linux, we do want to support that properly so I'll remove my block, pending signoff on the bug.

**Review by dmcilvaney — APPROVED** [review]

**Review by jslobodzian — APPROVED** [review]

**Pull request merged**
